import {useRef,useState,useEffect} from 'react';
import {useNavigate} from 'react-router-dom';
import {Settings,UserRound,Camera} from 'lucide-react';
import {useWorkspace} from '../store';
export function Avatar({profile}){return profile.avatar?<img src={profile.avatar} alt=""/>:<span>{profile.name?.trim().slice(0,1).toUpperCase()||<UserRound size={18}/>}</span>;}
export default function ProfileMenu(){
 const {state}=useWorkspace(),navigate=useNavigate(),ref=useRef();
 useEffect(()=>{const close=e=>{if(!ref.current?.contains(e.target))ref.current?.removeAttribute('open');};const key=e=>{if(e.key==='Escape')ref.current?.removeAttribute('open');};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key);};},[]);
 return <details className="profile-menu" ref={ref}><summary aria-label="Open profile and settings"><Avatar profile={state.profile}/></summary><div className="profile-dropdown"><strong>{state.profile.name}</strong>{state.profile.email&&<small>{state.profile.email}</small>}<button onClick={()=>{ref.current.removeAttribute('open');navigate('/app/settings');}}><Settings size={16}/>Profile & settings</button></div></details>;
}
export function ProfileEditor(){
 const {state,act}=useWorkspace(),[name,setName]=useState(state.profile.name),[email,setEmail]=useState(state.profile.email||''),[avatar,setAvatar]=useState(state.profile.avatar||''),[error,setError]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),file=useRef();
 const change=()=>{setSaved(false);setError('');};
 const upload=async event=>{const image=event.target.files?.[0];event.target.value='';if(!image)return;change();if(!['image/png','image/jpeg','image/webp'].includes(image.type)||image.size>3*1024*1024){setError('Choose a PNG, JPG or WebP image under 3 MB.');return;}setBusy(true);try{const bitmap=await createImageBitmap(image);const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const ctx=canvas.getContext('2d'),side=Math.min(bitmap.width,bitmap.height);ctx.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,128,128);bitmap.close();const data=canvas.toDataURL('image/webp',.8);if(data.length>40000)throw Error('Choose a smaller image.');setAvatar(data);}catch(e){setError(e.message||'This image could not be opened.');}finally{setBusy(false);}};
 return <form className="profile-editor settings-section" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await act('profile',{name,email,avatar});setSaved(true);}catch(e){setError(e.message);}finally{setBusy(false);}}}><h2>Your profile</h2><div className="profile-photo-row"><button type="button" className="profile-photo" aria-label="Change profile image" onClick={()=>file.current.click()} disabled={busy}><Avatar profile={{name,avatar}}/><Camera size={14}/></button><div><button type="button" className="text-button" onClick={()=>file.current.click()} disabled={busy}>Change image</button>{avatar&&<button type="button" className="text-button" onClick={()=>{setAvatar('');change();}}>Remove</button>}</div><input ref={file} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={upload}/></div><label>Name<input aria-label="Profile name" required maxLength={60} value={name} onChange={e=>{setName(e.target.value);change();}}/></label><label>Email<input aria-label="Profile email" type="email" maxLength={254} value={email} onChange={e=>{setEmail(e.target.value);change();}} placeholder="you@example.com"/></label><div className="profile-save"><button className="button small" disabled={busy}>{busy?'Saving…':'Save changes'}</button>{saved&&<span role="status">Saved</span>}</div>{error&&<p role="alert">{error}</p>}</form>;
}
