// npm run rem:demo — the three-minute REM story as a terminal narrative, with real numbers.
// Deterministic: in-memory MongoDB stand-in, ScriptedModel, local embeddings. Writes docs/DEMO-NUMBERS.md.
// --atlas: the same story on the Atlas Sandbox (MONGODB_URI, database REM_DB_NAME or "rem"), with
// search in Atlas; writes docs/DEMO-NUMBERS-ATLAS.md. Clears documents, keeps the search indexes.
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRem } from "../rem/index.js";
import { dayMetrics, review, runToCompletion, sleepMeasured } from "../rem/cycle.js";
import { GEN0, diffGenomes, renderDiff } from "../rem/harness.js";
import { mean, round, sum } from "../rem/util.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const t0 = performance.now();
const md = [];
const say = (line = "") => console.log(line);
const note = (line = "") => md.push(line);
const both = (line) => (say(line), note(`- ${line}`));
const block = (title, lines) => {
  say(title);
  for (const l of lines) say(`    ${l}`);
  md.push(`- ${title}`, "", "```", ...lines, "```", "");
};
const usd = (n) => `$${n.toFixed(4)}`;
const pct = (n) => `${n >= 0 ? "+" : ""}${Math.round(n * 100)}%`;
const signed = (n) => `${n >= 0 ? "+" : ""}${n}`;
const plural = (n, word) => `${n} ${word}${n === 1 ? "" : "s"}`;
const args = (a) => JSON.stringify(a.body ? { ...a, body: `(${a.body.length} chars)` } : a);
const section = (title) => {
  say(`\n━━ ${title} ${"━".repeat(Math.max(3, 74 - title.length))}`);
  note(`\n## ${title}\n`);
};

const atlas = process.argv.includes("--atlas");
let atlasDb = null;
if (atlas) {
  const { createMongoDb } = await import("../rem/db/mongo.js");
  atlasDb = await createMongoDb({ dbName: process.env.REM_DB_NAME || "rem" });
  for (const c of await atlasDb.listCollections({}, { nameOnly: true }).toArray())
    if (!c.name.startsWith("system.")) await atlasDb.collection(c.name).deleteMany({});
}
const outFile = atlas ? "DEMO-NUMBERS-ATLAS.md" : "DEMO-NUMBERS.md";
const rem = await createRem(atlasDb ? { db: atlasDb } : {});
const { db, world } = rem.ctx;
const checkpoints = db.collection("checkpoints");

say("REM · Replay · Evolve · Merge — agents that sleep, and wake up with a better harness.");
say(
  atlas
    ? `Engine: MongoDB Atlas Sandbox (database ${atlasDb.databaseName}, ${atlasDb.atlasSearch ? `search in Atlas: $rankFusion, ${atlasDb.vectorMode} vectors` : "app-side search"}), ScriptedModel.`
    : "Tonight's engine: in-memory MongoDB stand-in (driver-shaped), ScriptedModel, local embeddings.",
);
note(atlas ? "# REM demo numbers on the Atlas Sandbox\n" : "# REM demo numbers\n");
note("Generated by `npm run rem:demo` (deterministic: in-memory MongoDB stand-in, ScriptedModel, local");
note("embeddings). Every number below comes from that run; rerun the script to regenerate this file.");

// ── Day one: the durable-execution beat ─────────────────────────────────────────────────────
section("DAY ONE · W35 · harness v0 (gen 0)");
say("gen 0 is bare: no rules, no guardrails, every tool scope, no memory injection, every role on the large tier.");
const week = "W35";
const briefId = "run-weekly-brief-W35-d1";
rem.ctx.onEvent = (e) => {
  if (e.runId !== briefId) return;
  if (e.type === "planned") say(`plan (v${e.version}): ${e.plan.map((p) => p.replace(/^\d+\. /, "")).join(" · ")}`);
  if (e.type === "step") say(`  ${String(e.step).padStart(2)}  ${e.tool} ${args(e.args)} → ${e.error ? `error: ${e.error}` : e.summary}`);
  if (e.type === "effect") say(`      effect key ${e.effectKey.slice(0, 12)}… claimed in the ledger before ${e.tool} ran (${e.outcome})`);
  if (e.type === "resumed") say(`  ↻  change stream on connections saw a valid ${e.provider} token → run resumed from its checkpoint`);
};
say("▸ Start the weekly brief");
let brief = await rem.runTask("weekly-brief", { week, day: 1, runId: briefId, revokeAt: 3 });
const reconnectAsk = await db.collection("asks").findOne({ runId: briefId, kind: "reconnect" });
say(`  ✗  Google Drive token revoked after step 3 (deterministic revoke: connections.tokenState = "revoked")`);
say(`  ||  ${brief.status} before step ${brief.step + 1}; checkpoint holds ${brief.transcript.length} completed steps; ask queued: "${reconnectAsk.text}"`);
const retry = await rem.resumeRun(briefId);
const askCount = await db.collection("asks").countDocuments({ runId: briefId, kind: "reconnect" });
say(`      a retry while still revoked stays ${retry.status}; asks for this run: ${askCount} (it asks once)`);
say("▸ Reconnect Google Drive");
await rem.setConnection("drive", "valid");
await rem.settle();
brief = await checkpoints.findOne({ runId: briefId });
say(`  ✓  ${brief.status}: ${brief.final} ${plural(brief.turns, "step")} · ${usd(brief.usage.cost)} · ${plural(brief.interventions, "reconnect")}`);
const ledger = await db.collection("effects").find({ runId: briefId }).toArray();
const sent = world.state.sent.filter((m) => m.runId === briefId);
say("▸ Effects ledger for this run");
for (const e of ledger) say(`      ${e.effectKey.slice(0, 16)}…  ${e.tool}  step ${e.step}  ${e.status}  attempts ${e.attempts}`);
say(`      Sent folder: ${sent.length} message with header X-Effect-Key ${sent[0].headers["X-Effect-Key"].slice(0, 16)}… → sent exactly once`);
const r1 = await review(rem.ctx, brief);
say(`▸ Reviewer (same checkers as the gym): ${r1.verdict.collateral.length ? `✗ ${r1.verdict.collateral.join(", ")}` : "✓ clean"} → ${plural(r1.corrections, "correction")} stored as episodes`);
for (const kind of ["standup", "blockers", "follow-ups"]) {
  const r = await runToCompletion(rem, kind, { week, day: 1, runId: `run-${kind}-${week}-d1` });
  const { verdict } = await review(rem.ctx, r);
  say(`▸ ${r.title}: ${verdict.pass ? "✓" : `✗ ${verdict.collateral.join(", ")}`} (${plural(r.turns, "step")})`);
}
const dayOne = await checkpoints.find({ day: 1 }).toArray();
brief = await checkpoints.findOne({ runId: briefId });
both(`Weekly brief W35 under gen 0: Drive token revoked after step 3 → paused_for_auth with one ask ("${reconnectAsk.text}"); a retry while revoked stayed paused; reconnect → the change stream resumed it from its checkpoint.`);
both(`It finished in ${plural(brief.turns, "step")} for ${usd(brief.usage.cost)}; ledger: ${ledger.map((e) => `${e.tool} ${e.status}`).join(", ")}; ${sent.length} message in Sent (exactly once).`);
both(`Reviewer flagged ${r1.verdict.collateral.join(" and ")} → ${plural(r1.corrections, "correction")}.`);
both(`Day one: ${dayOne.filter((r) => r.verdict?.pass).length}/${dayOne.length} tasks passed, collateral ${sum(dayOne, (r) => r.verdict.collateral.length)}, cost ${usd(sum(dayOne, (r) => r.usage.cost))}, ${plural(sum(dayOne, (r) => r.interventions), "human intervention")}.`);

// ── Night one ───────────────────────────────────────────────────────────────────────────────
section("NIGHT ONE · sleep");
const n1 = await sleepMeasured(rem, week);
const b = n1.brief;
both(`Replay: ${b.replay.episodes} episodes from ${b.replay.runs.length} runs.`);
both(
  `Merge: ${b.merge.episodesIn} observation, correction and demonstration episodes → ${b.merge.facts} facts → ${b.merge.memoriesAfter} memories ` +
    `(${b.merge.folded} facts folded in); ${b.merge.contradictionsResolved} contradiction resolved by recency; ${b.merge.retired} resolved blocker retired; ` +
    `${b.merge.noiseDropped} noise episodes dropped; ${b.merge.expiring} episodes set to expire by TTL.`,
);
both(
  `Memory: searchable store ${n1.before.size} → ${n1.after.size} items; duplicate ratio ${n1.before.duplicateRatio} → ${n1.after.duplicateRatio}; ` +
    `contradictions ${n1.before.contradictions} → ${n1.after.contradictions}; precision@k ${n1.before.precisionAtK} → ${n1.after.precisionAtK}.`,
);
for (const s of b.distill.skills)
  both(`Distill: skill "${s.name}" from ${s.evidence} traces (the human demonstration + day one's run); sandbox test ${s.test.pass ? "passed" : "failed"} in ${plural(s.test.steps, "step")}; status ${s.status}.`);
both(`Evolve: weaknesses mined on the train set: ${b.evolve.patterns.map((p) => `${p.title} (${p.tasks.join(", ")})`).join("; ")}.`);
for (const e of b.evolve.edits) {
  const p = e.prediction,
    o = e.outcome.train;
  if (!o) {
    both(`Queued as an ask: ${e.description} (${e.outcome.reason})`);
    continue;
  }
  both(
    `${e.outcome.status === "accepted" ? "✓ Accepted" : "✗ Rejected"}: ${e.description} — predicted ${signed(p.passDelta)} pass, ${pct(p.costDelta)} cost; ` +
      `observed ${signed(o.passDelta)} pass, ${pct(o.costDelta)} cost` +
      (e.outcome.status === "rejected" ? ` — ${e.outcome.reason}: ${e.heldOutRegressedTitles.join(", ")}` : ""),
  );
}
block(`Commit: harness v${b.harness.to} (parent v${b.harness.from})`, b.harness.diffText);
both(
  `Gym: train ${b.evolve.baseline.train.passed}/${b.evolve.baseline.train.tasks} → ${b.evolve.fitness.train.passed}/${b.evolve.fitness.train.tasks}, held-out ${b.evolve.baseline.heldOut.passed}/${b.evolve.baseline.heldOut.tasks} → ${b.evolve.fitness.heldOut.passed}/${b.evolve.fitness.heldOut.tasks}, ` +
    `collateral ${b.evolve.baseline.all.collateral} → ${b.evolve.fitness.all.collateral}.`,
);
for (const a of b.asks) both(`Ask queued for the morning: "${a.text}"`);

// ── Morning ─────────────────────────────────────────────────────────────────────────────────
section("MORNING");
for (const a of await db.collection("asks").find({ status: "open", kind: "skill.autonomous" }).toArray()) {
  say(`? ${a.text}`);
  await rem.decide(a._id, "approve");
  both(`Approved "${a.text}" → skill ${a.skill} is autonomous; the decision is stored and shapes future asks.`);
}
const d1 = await dayMetrics(rem.ctx, { day: 1, week, before: n1.before, after: n1.after, withoutSleep: n1.withoutSleep, brief: b });
rem.ctx.onEvent = null;
const rerun = await runToCompletion(rem, "weekly-brief", { week, day: null, runId: "run-weekly-brief-W35-morning" });
const rr = await review(rem.ctx, rerun);
const again = await checkpoints.findOne({ runId: rerun.runId });
const row = (label, r, v) =>
  `${label.padEnd(8)} ${plural(r.turns, "step")} · ${usd(r.usage.cost)} · ${plural(r.interventions, "intervention")} · collateral ${v.collateral.length} · ${Math.round(r.latencyMs / 1000)}s`;
say("▸ Same task again (weekly brief W35) under the new harness and the approved skill:");
say(`  ${row("day one", brief, r1.verdict)}`);
say(`  ${row("morning", again, rr.verdict)}`);
note(`- Weekly brief W35 again under v${again.harnessVersion} with the autonomous skill: ${brief.turns} → ${again.turns} steps, ${usd(brief.usage.cost)} → ${usd(again.usage.cost)}, interventions ${brief.interventions} → ${again.interventions}, collateral ${r1.verdict.collateral.length} → ${rr.verdict.collateral.length}.`);
const v1 = await rem.harness();
block(`Harness diff gen 0 → v${v1.version}:`, renderDiff(diffGenomes(GEN0, v1.genome)));

// ── Five simulated days ─────────────────────────────────────────────────────────────────────
section("FIVE SIMULATED DAYS");
say("Days 2–5 run the same way; every night validates real edits on the gym. One crash is injected per day after the brief's send.");
const rest = await rem.simulateDays(4);
const days = [d1, ...rest];
const head = ["Day", "Week", "Harness", "Passed", "Collateral", "Steps", "Cost", "Interventions", "Memory (no sleep)", "Duplicates (no sleep)", "Contradictions (no sleep)", "Precision@k (no sleep)", "Held-out after night", "Prediction error"];
const cells = days.map((d) => [
  d.meta.day,
  d.meta.week,
  `v${d.meta.harnessVersion}→v${d.meta.harnessAfter}`,
  `${d.passed}/${d.tasks}`,
  d.collateral,
  d.steps,
  usd(d.cost),
  d.interventions,
  `${d.memory.after.size} (${d.memory.withoutSleep.size})`,
  `${d.memory.after.duplicateRatio} (${d.memory.withoutSleep.duplicateRatio})`,
  `${d.memory.after.contradictions} (${d.memory.withoutSleep.contradictions})`,
  `${d.memory.after.precisionAtK} (${d.memory.withoutSleep.precisionAtK})`,
  `${d.gym.heldOut.passed}/${d.gym.heldOut.tasks}`,
  d.predictionError ?? "–",
]);
const widths = head.map((h, i) => Math.max(h.length, ...cells.map((c) => String(c[i]).length)));
say(head.map((h, i) => h.padEnd(widths[i])).join("  "));
for (const c of cells) say(c.map((v, i) => String(v).padEnd(widths[i])).join("  "));
note(`| ${head.join(" | ")} |`);
note(`| ${head.map(() => "---").join(" | ")} |`);
for (const c of cells) note(`| ${c.join(" | ")} |`);
note("\nMemory columns: the searchable store after each night; in parentheses, a shadow store that never sleeps.");

const final = await rem.harness();
const effects = await db.collection("effects").find({}).toArray();
const keys = new Set(world.executed.map((e) => e.effectKey));
section("CURVE + CLOSE");
both(`Pass rate ${days[0].passRate} → ${days.at(-1).passRate}; collateral ${days[0].collateral} → ${days.at(-1).collateral}; cost per day ${usd(days[0].cost)} → ${usd(days.at(-1).cost)}; interventions ${days[0].interventions} → ${days.at(-1).interventions}.`);
both(`Memory after five days: ${days.at(-1).memory.after.size} memories vs ${days.at(-1).memory.withoutSleep.size} raw items without sleep; precision@k ${days.at(-1).memory.after.precisionAtK} vs ${days.at(-1).memory.withoutSleep.precisionAtK}.`);
both(`Exactly-once: ${effects.filter((e) => e.status === "committed").length} effects committed, ${world.executed.length} executed in the world, ${world.executed.length - keys.size} duplicates; ${effects.filter((e) => e.outcome === "reconciled").length} injected crashes reconciled from the ledger.`);
const errors = [b, ...rest.map((d) => d.brief)].filter((x) => x.evolve.edits.length).map((x) => round(mean(x.evolve.edits, (e) => e.outcome.predictionError), 3));
both(`Proposer prediction error by night: ${errors.join(" → ")} (lower once each edit type has a track record).`);
both(`Gym: held-out ${b.evolve.baseline.heldOut.passed}/${b.evolve.baseline.heldOut.tasks} → ${rest.at(-1).gym.heldOut.passed}/${b.evolve.baseline.heldOut.tasks}, train ${b.evolve.baseline.train.passed}/${b.evolve.baseline.train.tasks} → ${rest.at(-1).gym.train.passed}/${b.evolve.baseline.train.tasks}, gym cost ${usd(b.evolve.baseline.all.cost)} → ${usd(rest.at(-1).gym.cost)}.`);
block(`Harness diff gen 0 → v${final.version}:`, renderDiff(diffGenomes(GEN0, final.genome)));
note("\nTrack record by edit type (an aggregation over `edits`, fed back into the proposer):\n");
note("| Edit type | Edits | Accepted | Rejected | Mean prediction error |");
note("| --- | --- | --- | --- | --- |");
for (const r of await rem.trackRecord()) note(`| ${r._id} | ${r.edits} | ${r.accepted} | ${r.rejected} | ${round(r.meanError, 3)} |`);
await rem.close();
await fs.mkdir(path.join(here, "../docs"), { recursive: true });
if (atlas) note(`\nEngine: Atlas database ${atlasDb.databaseName}, search ${atlasDb.atlasSearch ? `$rankFusion over ${atlasDb.vectorMode} vector + Atlas Search indexes` : "app-side"}, ScriptedModel. Wall time ${Math.round(performance.now() - t0)} ms.`);
// The Atlas record follows the no-em-dash house style; the in-memory file keeps its original format.
const text = atlas ? md.join("\n").replace(/ \u2014 /g, ": ").replace(/\u2014/g, "-") : md.join("\n");
await fs.writeFile(path.join(here, `../docs/${outFile}`), `${text}\n`);
say(`\nWrote docs/${outFile} · ${Math.round(performance.now() - t0)} ms`);
if (atlasDb) await atlasDb.close();
